### ISSUE TITLE
Check is it possible to Scrap daraz.pk. If possible then write script in the repo other wise drop the idea and find a new one.

### ISSUE THREAD

**Issue by asadali27232** [asadali27232/FYP#1]

**Comment by HaroonMalik771** [comment]
I will check and find the solution to Scrap the daraz.pk

**Comment by asadali27232** [comment]
Not a proper and secure solution was found to scrape a website like daraz.pk as they have a very advanced AI-based system to detect crawlers and block them so we switched to another idea for our FYP.
