### ISSUE TITLE
Write FYP Proposal by dividing headings between group member. Every one complete their assigned headings from the proposal and commit a file named 'yourname_proposal.doc' inside the documentation folder in project repo.

### ISSUE THREAD

**Issue by asadali27232** [asadali27232/FYP#4]

**Comment by asadali27232** [comment]
Started woking on the diagrams that needed to be added to the proposal i.e. Gantt chart, and flow chart etc.

**Comment by HaroonMalik771** [comment]
I have completed my assign Task

**Comment by asadali27232** [comment]
CONGRATS Team!
The proposal is submitted successfully.....!
Now we are officially registered for FYP at COMSATS.
Move forward to other issues.
